version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    environment:
      DATABASE_URL: postgresql://docker:docker@postgres:5432/urlshortener
      REDIS_URL: redis://:docker@redis:6380
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: urlshortener
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    command: ["redis-server", "--requirepass", "docker"]
    ports:
      - "6380:6380"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
